// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPkgeWZav5gynxML9-FaExlfN0Ue_gUOE',
    appId: '1:771703545481:web:585a04110e566f7d6a7058',
    messagingSenderId: '771703545481',
    projectId: 'online-course-app-trng',
    authDomain: 'online-course-app-trng.firebaseapp.com',
    storageBucket: 'online-course-app-trng.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZlYRl8z7A5DA99-DGjq2gykq9N5GSJHQ',
    appId: '1:771703545481:android:46703888428adbcc6a7058',
    messagingSenderId: '771703545481',
    projectId: 'online-course-app-trng',
    storageBucket: 'online-course-app-trng.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCUyypKP6SrbHgMKIrPS-oK880CVmfN6A',
    appId: '1:771703545481:ios:18eb0b1c16d91d026a7058',
    messagingSenderId: '771703545481',
    projectId: 'online-course-app-trng',
    storageBucket: 'online-course-app-trng.appspot.com',
    iosClientId: '771703545481-os5jqb4vsbf9kkhp47335i0dqhgp9auu.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCUyypKP6SrbHgMKIrPS-oK880CVmfN6A',
    appId: '1:771703545481:ios:18eb0b1c16d91d026a7058',
    messagingSenderId: '771703545481',
    projectId: 'online-course-app-trng',
    storageBucket: 'online-course-app-trng.appspot.com',
    iosClientId: '771703545481-os5jqb4vsbf9kkhp47335i0dqhgp9auu.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineLearningApp',
  );
}
